version: '3.7'

services:
  mongo:
    image: mongo:4.4.2
    ports:
      - 27017:27017
    volumes:
      - mongoVolume:/data/db
    networks:
      - tournaProNetwork

volumes:
  mongoVolume:

networks:
  tournaProNetwork:
