version: '3.7'

services:
  frontend:
    build:
      args:
        - "API_URL_BASE=http://192.168.99.100:${BACKEND_PORT}"
  
  backend:
    environment:
      - "TOURNAPRO_FRONTEND_ORIGIN=http://192.168.99.100:${FRONTEND_PORT}"