version: '3.7'

services:
  backend:
    image: tourna-pro-backend
    build:
      context: ./tourna-pro-backend
      dockerfile: Dockerfile
      args:
        - "PORT=${BACKEND_PORT_INTERNAL}"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT_INTERNAL}"
    environment:
      - "TOURNAPRO_MONGO_URL=mongodb://mongo/TournaProDB"
      - "TOURNAPRO_PORT=${BACKEND_PORT_INTERNAL}"
      - "TOURNAPRO_CONNECTION_DELAY=5000"
    networks:
      - tournaProNetwork
    depends_on:
      - mongo
  
  frontend:
    image: tourna-pro-frontend
    build:
      context: ./tourna-pro-webapp
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT_INTERNAL}"
    networks:
      - tournaProNetwork    

  mongo:
    image: mongo:4.4.2
    ports:
      - "27017:27017"
    volumes:
      - "mongoVolume:/data/db"
    networks:
      - tournaProNetwork

volumes:
  mongoVolume:

networks:
  tournaProNetwork:
